### ISSUE TITLE
scan from tests not working

### ISSUE THREAD

**Issue by jschoch** [CargoSense/ex_aws#17]
I get the following when running the scan from your dynamodb test

```elixir

iex(27)> Dynamo.scan("Users",
...(27)>       limit: 12,
...(27)>       exclusive_start_key: [api_key: "api_key"],
...(27)>       expression_attribute_names: [api_key: "#api_key"],
...(27)>       expression_attribute_values: [api_key: "asdfasdfasdf", name: "bubba"],
...(27)>       filter_expression: "ApiKey = #api_key and Name = :name")
{:error,
 {:http_error, 400,
  "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"Message\":\"ExpressionAttributeNames contains invalid key: Syntax error; key: \\\"api_key\\\"\"}"}}
```

**Comment by benwilson512** [comment]
Hey jschoch, the examples I have in those particular tests merely test the FORM of the data to sent to AWS, they are not intended to provide working examples. For example, you would need a Users table configured with an ApiKey column and such in order to make this work.

The only test examples that ought towork out of the box are those within the `dynamo/integration_test.exs` and similarly named files.

I should probably write a comment in these test files to that effect though.

**Comment by benwilson512** [comment]
I should also add that you should pay careful attention to the particular client used. The Dynamo integration tests for example actually run against dynamodb local, which is why I can safely delete tables without worrying about touching real data. I definitely should add some documentation to the tests.

**Comment by jschoch** [comment]
thanks, silly mistake

i also noticed you call out #query but actually call scan here

https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/dynamo_test.exs#L31

I have a few other comments i'll put in other issues.  Great library btw, erlcloud isn't being developed further.

**Comment by benwilson512** [comment]
Good catch! Feedback is appreciated, keep it coming.
