### ISSUE TITLE
Concurrent piecewise downloads

### ISSUE THREAD

**Issue by heri16** [CargoSense/ex_aws#173]
Feature request to use Multipart download when doing s3:GetObject

**Comment by benwilson512** [comment]
I think this is a fine feature, and we need the same for downloads.

**Comment by benwilson512** [comment]
To be clear, this will not be what the `get_object` function does. As I've talked about elsewhere, functions that match a clear AWS operation name will simply do that operation. However, `S3.download_object` or some similarly named function will handle more complex download procedures, built off of the primative `get_object`.

This is why I'll be changing the name of this issue slightly.

**Comment by heri16** [comment]
help no longer wanted? :)

**Comment by heri16** [comment]
I wrote something that will help.

```elixir
with {:ok, _resp = %{headers: headers} } <- ( ExAws.S3.head_object(bucket_name, object_key) |> ExAws.request(s3_config) ),
      {_, val} <- ( headers |> List.keyfind("Content-Length", 0, nil) ),
      {content_length, _} <- Integer.parse(val),
      do
        Stream.unfold({0, content_length}, fn
          {from_offset, to_offset} when (from_offset+1024) < to_offset -> 
            { {from_offset, from_offset + 1024}, {from_offset + 1025, to_offset}}
          {from_offset, to_offset} when (from_offset+1024) >= to_offset ->
            { {from_offset, to_offset}, nil}
          _ -> nil
        end)
        |> Stream.map(fn {from_offset, to_offset} ->
          [range: "bytes=#{from_offset}-#{to_offset}"]
        end)
        |> Enum.map(fn opts ->
          Task.async(fn ->
            ExAws.S3.get_object(bucket_name, object_key, opts) |> ExAws.request(s3_config)
          end)
        end)
        |> Stream.map(&Task.await(&1))
        |> Enum.reduce(StringIO.open(""), fn
          {:ok, _resp = %{body: chunk}, sio ->
            IO.binwrite(sio, chunk)
          _else ->
            {:halt, sio}
        end)
        |> StringIO.contents
      end
```

**Comment by benwilson512** [comment]
Interesting approach!

There's a few issues though, although since I haven't articulated my goals very clearly here it's hardly your fault ;)

- [ ] unbounded concurrency: Concurrent downloads are good, but for a gigabyte file you're gonna start 1 gigabyte/1024 byte processes which is simply too many. Switching things up to say "ah we're gonna just go with N downloader processes and take filesize / n to get chunk size" isn't optimal either, because with a gigabyte file if you want at most 10 downloaders then each is downloading 100 mb, and it's entirely possible that some will finish well before the others.
- [ ] Downloading to file vs downloading in memory. For large files we probably want an option to download to a file, although obviously a File.open could be used in lieu of StringIO.open. For the purposes of doing stuff in memory though, it would be better to simply concat all the body chunks, binwriting to StringIO does a bunch of unnecessary copying.
- [ ] Supervision and failure semantics. The more requests that are made the greater the probability of failure. ExAws requests do have some build in retry mechanisms, so maybe that's enough, but right now one failure will nuke the other related processes, and we may want finer grained control.

Those are sort of the high level objectives that I want to handle here. I've got some code sketched out somewhere I'll try to fill out more and get up for commentary.

**Comment by heri16** [comment]
I think the latest pull request #196 addresses this issue. Closing.
