### ISSUE TITLE
add bang version of stream_*

### ISSUE THREAD

**Issue by jschoch** [CargoSense/ex_aws#18]
would be great to have stream_query!(...)  etc etc.

**Comment by benwilson512** [comment]
Good call. Will do the same for Kinesis.stream_records!

**Comment by benwilson512** [comment]
Well actually I think this is an interesting point of discussion. I wonder if stream_query stream_scan and so on ought to act like stream_records currently does, where in it always just returns a lazy enumerable, and if there are errors those are handled on an item by item basis.

In favor of that plan is that while a stream of items from say `stream_scan` may start off fine there's nothing stoping future requests from failing, and that' why right now I do stuff like

```elixir 
{:error, items} ->
          {[{:error, items}], :quit}

{:ok, %{"Items" => items, "LastEvaluatedKey" => key}} ->
          {items, {fun, %{exclusive_start_key: key}}}
```
Because a given new request to get more items _can_ fail.

Thoughts? @bruce may also have input.

**Comment by benwilson512** [comment]
Based on the discussion in IRC, all streams will return bare enumerables that return the desired items, and raise on error. This obviates the need for bang functions for streams.
