### ISSUE TITLE
DynamoDB put_item with binary data

### ISSUE THREAD

**Issue by chris-die** [CargoSense/ex_aws#192]
I can't work out how to use `ExAws.Dynamo.put_item` to save binary data to a DynamoDB table.

If I provide a bit string to put_item I receive a Poison encode error. If I base 64 encode the data then the data is saved to DynamoDB as a string.

```
binary_data = <<some binary data>>
ExAws.Dynamo.put_item("MyTable", %{my_field: binary_data})

** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
```

```
ExAws.Dynamo.put_item("MyTable", %{my_field: Base.encode64(binary_data)})
{:ok, %{}} # But my_field contains a string, not a binary.
```

Is there a way I can explicitly define the data types of the map I pass to put_item?

**Comment by benwilson512** [comment]
Hey there!

I'll respond with greater length tomorrow, but this is the purpose of the Encodable protocol. As I'm sure you're aware, the actual data sent to dynamo uses a bunch of type tags that look like https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/dynamo/encoder_test.exs#L11

If you want to provide custom encoding information for a given type, you should create a struct for that record and implement the encodable protocol for it. I will create a relevant example probably tomorrow, out and about at the moment sorry!

**Comment by chris-die** [comment]
Thanks @benwilson512, I figured it out.

You even mention it in your (docs)[https://hexdocs.pm/ex_aws/ExAws.Dynamo.Client.html] so I should really have a spent a bit more time experimenting.

But a question: looking at (dynamo/encodable.ex) [https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo/encodable.ex] I see that the default encoder implementation for bitstrings is to send them to DynamoDB as a string data type.

Would it not make more sense to send them as a binary data type?

As I see it (and please correct me if I'm wrong) there's currently no way using the default encodings to send a binary data to DynamoDB.

**Comment by benwilson512** [comment]
Glad you figured it out.

The reason that the default for bitstrings is to send as a string type is that `"hello"` in Elixir is a bitstring. Now, I could try to case off of `String.valid?` or something to choose `"S"` or `"B"` but this will incur a cost as String.valid? has to walk the whole string linearly.

You do have another option I believe. The encode encode function is idempotent, so if you provide an already tagged value it will not be re-tagged as something else. Thus if instead of `ExAws.Dynamo.put_item("MyTable", %{my_field: binary_data})` you did `ExAws.Dynamo.put_item("MyTable", %{my_field: %{"B" => binary_data}})` it will use the provided type tag. I should write a test to that effect.

**Comment by chris-die** [comment]
Yeah, I noticed that you allow for tagged values. Nice.

I'm happy with using a struct and implementing the encodable protocol.

Thanks for your help and nice job on the library.

**Comment by benwilson512** [comment]
Thanks!
