### ISSUE TITLE
streamlining 

### ISSUE THREAD

**Issue by jschoch** [CargoSense/ex_aws#20]
seems like having to pipe to decode is a bit terse, would you consider some short cuts to return a decoded item or list?  something

```
get_map(table_name,primary_key) :: {Atom, Map}
query_maps( table_name,primary_key) :: {Atom,List}
```

you could also do

```
get_struct(table_name,primary_key,struct_name)
query_structs(...)
```
also, it is unclear how you use a primary_key and range_key with get_item

finally wondering if there is a way to annotate the primary key, range key and even table_name in the module.  it would be nice to derive this for things like

```elixir
defmodule User do
  @table_name "Users"
  @primary_key "email"
  @range_key "age"
  @derive [ExAws.Dynamo.Encodable]
  defstruct [:email, :name, :age, :admin]
end


user = %User{admin: false, age: 23, email: "bubba@foo.com", name: "Bubba"}
put_item(user)
new_user = %User{admin: true, age: 33, email: "baz@foo.com", name: "Unf"}
update_item(new_user)
```

**Comment by benwilson512** [comment]
I absolutely see the value of this kind of functionality, but I believe that it's beyond the scope of this project. Some kind of Dynamo based modeling layer would absolutely be useful (an ecto adapter in particular would be awesome), and I hope this library would be useful to that end.

However such functionality, particularly the latter model suggestion, does not belong within the client specification, and there isn't a good place for it within the current scope of the project in general. I'm somewhat on the fence about making it easier to get certain data types back, but feel strongly that they don't belong in the Client spec either. On the whole I think it's better we wait and revisit the question, as I'd like to have a more comprehensive way for defining result processors instead of one off functions here and there.

Fortunately the current situation isn't all that bad, decoding is only just a function call.

WRT primary key w/ ranges and get_item you're right I haven't given that much thought. I haven't used any primary keys with ranges and seem to have passed over their use. Will create a separate issue for that and look into it.
