### ISSUE TITLE
Credentials from ec2 role - instance metadata

### ISSUE THREAD

**Issue by stocks29** [CargoSense/ex_aws#30]
It would be awesome if this client worked with ec2 roles, pulling credentials from instance metadata. Even better would be to use the default credentials chain that the amazon-developed clients use :)

**Comment by benwilson512** [comment]
That definitely sounds cool, but I'm a bit confused about what you mean by "pulling credentials from instance metadata". Can you link to some AWS documentation related to what you mean? As far as roles are concerned, this client definitely works with roles in the sense that it uses regular IAM tokens. You can assign those tokens to any role(s) you like, and those restrictions / permissions will apply to those keys.

As far as default credentials go, I'm a bit confused there too. How can I possibly embed tokens in this library that will work with everyone's account?

**Comment by stocks29** [comment]
The way it works is, when launching a new ec2, you assign it a role, then the client library, when making a service request, first calls the identity metadata service to retrieve temporary aws credentials to use for the service request.



Here is a high level doc that talks about IAM roles. Step 5 is if particular interest.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

Here is a doc on contacting the identity metadata service

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

Newer aws clients tend to use a "default credential provider chain" which looks for credentials in various places from least to most expensive. IIRC it is.....

1. Explicitly provided credentials
2. Environment variables
3. Identity metadata service

I've been pretty absorbed in aws in several languages lately so please do let me know if you have any questions on this stuff :)

**Comment by stocks29** [comment]
Here are java docs that talk about the default credential provider chain

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by benwilson512** [comment]
Ah ok that's cool. We can definitely do this. My initial sense is that it in your mix config you could do something like:

```elixir
config :ex_aws,
    access_key_id: Instance.meta("role")["AccessKeyId"],
    secret_access_key: Instance.meta("role")["SecretAccessKey"]
```

Ignoring the question of exactly what module would be responsible for holding the meta-data fetching stuff (using `Instance` for the moment) does that seem like a useful approach? Obviously it isn't something where we want to be making the request every time the keys are used, so by putting it in the config it would get pulled at the start of runtime and then cached in the config.

**Comment by benwilson512** [comment]
On a further reading of the docs, it looks like something more along the lines of
```elixir
config :ex_aws,
  access_key: [instance_meta: "role"]
```
Could be used. Thoughts?

**Comment by stocks29** [comment]
Actually, the credentials provided by the instance metadata service are only temporary credentials which are automatically rotated by the metadata service. Here's an excerpt from the docs:

> These security credentials are temporary and we rotate them automatically. We make new credentials available at least five minutes prior to the expiration of the old credentials.

Since the service lives on the local EC2, it's not super expensive to retrieve them, although I suppose you could have a background process updating them periodically. The typical approach I've seen is to just to call the instance metadata before each request though, since it's not that expensive.

If we wanted to mimic the AWS-developed java client's credential provider chain directly, the approach would be:

1. Check for keys in AWS environment variables (AWS_ACCESS_KEY_ID and AWS_SECRET_KEY), using those credentials if present
2. Check for keys in system properties (this would likely be Application.get_env() since that is the closest thing to java system properties).
3. Check for existence of credential profiles file (~/.aws/credentials), use credentials from there if present
4. Lastly, if no credentials were found at any of the above, fall back to using the instance profile credentials from the ec2 metadata service

This approach is nice because it allows you to easily override credentials. Honestly though, once you've used IAM roles and the EC2 metadata service, it's hard to use anything else. It's just so convenient and safe when you're deploying to EC2 or elastic beanstalk.

**Comment by stocks29** [comment]
Ha, sorry, I totally missed the key_refresh edit. That could definitely work. 

My typical approach is to use env vars for dev environments and then IAM roles via ec2 metadata in prod environments. 

I'm not sure I could get this working as-is with an OTP release since this...

```elixir
config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY")
```

...is evaluated at compile time, not run time. For OTP releases (built with exrm) with won't work.

Phoenix works around this like so:

```elixir
config :ex_aws,
  access_key_id: {:system, "AWS_ACCESS_KEY_ID"},
  secret_access_key: {:system, "AWS_SECRET_ACCESS_KEY"}
```

Then ex_aws would need to match the tuple and execute the function at run-time. Alternatively, if the chain were hard-coded then it's just a matter of using the option that works best for the developers needs. This is how erlcloud works, although iirc, it only checks (1) credentials passed directly to functions, (2) env vars, (3) ec2 instance metadata.

**Comment by stocks29** [comment]
If I were writing this, I'd probably just hard-code the default credential provider chain (long-term that could be a mix configuration setting where you specify a callback module which defines the chain if extra configuration were desired) to stay as close to the official aws library as possible.

I'm super excited about ex_aws btw! I'll be happy to move away from erlcloud and stop translating char lists to binaries and back. Thanks for writing ex_aws! :)

**Comment by benwilson512** [comment]
I'm happy to hear you're finding this useful! Good point about the releases. I think I'm going to stick with an explicit configuration over an implicit one, for the same reason that I don't by default look at the system env right now. AWS keys can wield a lot of power, and since Mix has such an easy to use central configuration system, the cost of explicitness is very low. Nonetheless I definitely want to make it easy to specify whether to use a file, system env, or instance credentials.

The overhead for requesting the instance meta-data is indeed low, on the order of a couple ms. On the one hand, most requests to other AWS services will take longer than that. On the other hand, caching the result in ETS and refreshing it periodically with a genserver is trivial. I think I'll work on getting the instance meta-data keys working, and then optimize with ETS.

**Comment by benwilson512** [comment]
This is on the TODO shortlist, definitely a feature I want to use.

**Comment by stocks29** [comment]
Sounds awesome to me! :)

**Comment by jannekai** [comment]
Great progress on the library! 

Hope to see the instance metadata support too, since we are using it with IAM roles so we don't have to worry about access keys during deployment etc.

I did write a wrapper on top of erlcloud and part of it was using explicit config in every API call. Since I didn't want to worry about expiring credentials, i went with the genserver updater process fetching credentials and writing whole config to ETS table. The gist below contains that part of the code. Note that it hasn't been used in production yet, but seems to work on elastic beanstalk dev installation pretty reliably. Hope it's useful.

https://gist.github.com/jannekai/fb3135f39a1c7c48a5da

I do agree with @stocks29 that supporting the provider chain would be nice. It might even be nice to allow extending the whole configuration setting with by defining a :config_provider setting and calling the configured concrete implementation. With one or maybe two concrete implementations most users probably wouldn't need to do any custom coding either.

https://gist.github.com/jannekai/b0f6151ba780089edeff

**Comment by benwilson512** [comment]
This is extremely helpful stuff thank you! What would be the value you would specify as config_provider? Something like:

```
defmodule Config.Provider.Default do
   def get do
      # check mix config
      # then check ENV
      # then check instance meta
   end
end

config :ex_aws,
  config_provider: Config.Provider.Default
```

**Comment by benwilson512** [comment]
I should add that one of the challenges in doing this that has contributed to its delay has been my desire to keep configuration like this on a per client basis, and allow configurable http clients and JSON parsers. So for example some level of configuration parsing needs to happen for a given client prior to obtaining keys to determine what http client / codecs will be used in order to make instance meta-data requests. Totally doable, but it's required a bit of extra thought in order to enable.

**Comment by benwilson512** [comment]
OK! So here's what I have in #35 as of right now, and I may declare this good enough for the time being unless there's functionality I'm missing somehow. The following works:

```elixir
# In mix config
config :ex_aws,
  access_key_id: {:role, "MyRole"},
  secret_access_key: {:role, "MyRole"}

# Also works
config :ex_aws,
  access_key_id: [{:system, "SYSTEM_ENV_VAR_ID"}, {:role, "MyRole"}],
  secret_access_key: [{:system, "SYSTEM_ENV_VAR_SECRET"}, {:role, "MyRole"}]

# which is exactly equivalent to
config :ex_aws,
  access_key_id: [system: "SYSTEM_ENV_VAR_ID", role: "MyRole"}],
  secret_access_key: [system: "SYSTEM_ENV_VAR_SECRET", role: "MyRole"]
```

The latter will try the system environment and if those fail, will grab the role. I know that there's a bit of redundancy in that you have to specify the role twice, I'll spend some time thinking about that. OTOH it provides a very easy way to setup the desired behaviour of "try these env keys, otherwise fallback to this role".

I've moved away from the idea of having a provider module, because that's basically what a client _IS_. If you want fancy configuration options, you can just do:

```elixir
defmodule MyDynamo do
  use ExAws.Dynamo.Client

  def config do
    %__MODULE__{}
    |> ExAws.Config.get  # sets defaults
    |> my_fancy_overrides
  end
end
```

Then you do `MyDynamo.list_tables` or whatever else you want to do.

In any case, are there any use cases not covered by the config via tuples, config via list of tuples, or config via client modules?

**Comment by stocks29** [comment]
Looks to me like this will work although I don't believe it is necessary to provide a role name since each EC2 can only have 1 role assigned to it and the role name can be automatically discovered by going to this endpoint first "http://169.254.169.254/latest/meta-data/iam/security-credentials/". The downside to explicitly specifying the role name in the config here is you'll have to change it if/when you change the role name. So if you wanted to deploy to two instances with two different roles, you'd have to have different configuration for each.

If you added a provider module, you could pretty easily support a provider chain with the way the config works, like the example below. 

```elixir
# in config.exs
config :ex_aws,
  access_key_id: ExAws.Config.CredentialProvider.default_access_key_provider_chain(),
  secret_access_key: ExAws.Config.CredentialProvider.default_secret_key_provider_chain()

# in ExAws.Config.CredentialProvider
def default_access_key_provider_chain() do
    [system: "AWS_ACCESS_KEY_ID", role: "MyRole"}]
end
def default_secret_key_provider_chain() do
    [system: "AWS_SECRET_ACCESS_KEY", role: "MyRole"]
end
```

While I don't think it's a huge problem, since the access and secret keys are treated separately, if you typically used IAM roles but wanted to temporarily override with environment variables and you fat-fingered one of the env vars when setting them, you could end up pulling, for example, the access key from an env var and the secret key from metadata which obviously wouldn't work and could be very difficult to diagnose. If you were to treat them as a pair, you could add validation checks to ensure that both pieces are coming from the same source.

I'm not sure exactly how that would look though. Perhaps something like this?

```elixir
config :ex_aws,
  credentials: [
    {:environment, "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"}, 
    :role, 
    {:static, "actual-access-key", "actual-secret-key"}]
```

Just my 2 cents. Hopefully this is helpful :)

**Comment by benwilson512** [comment]
```bash
$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

**Comment by benwilson512** [comment]
Ah if you can determine the role programmatically then I won't require it to be passed in. I'm not too worried about people fat fingering the environment variables, 99% of the time they're just copying it from the readme anyway. How about:

```elixir
config :ex_aws,
  access_key_id: [{:system, "SYSTEM_ENV_VAR_ID"}, :role],
  secret_access_key: [{:system, "SYSTEM_ENV_VAR_SECRET"}, :role]
```

**Comment by benwilson512** [comment]
I'm not sure I get the value of having a separate module is to hold that list. ExAws.Config has a bunch of defaults, but I don't include methods to retrieve AWS keys there, instead preferring that people set that in their mix config. If they're gonna be pasting something in mix config, I'm not clear on the value of having them paste something like:

```elixir
config :ex_aws,
  access_key_id: ExAws.Config.CredentialProvider.default_access_key_provider_chain(),
  secret_access_key: ExAws.Config.CredentialProvider.default_secret_key_provider_chain()
```
vs
```elixir
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
```

**Comment by stocks29** [comment]
Just consistency between different language clients and convenience in lieu of the default being (no config) being the default provider chain.

Honestly, it would be my preference that the default, without specifying any config, matched the default provider chain of other languages since it is super convenient. It would be nice if you only had to specify the config if you wanted to override. This is currently how erlcloud works as well.

If it isn't the no-config default, the benefit of modularizing it is if amazon decides to change it, the default_* functions could be updated to keep in sync, assuming the new behavior is even nicer. Then those that upgrade get the newer behavior for free instead of having to manually update their configs. 

It's also familiar for folks coming from official amazon clients so less barrier to entry although it wouldn't be a high hurdle.

Just my 2 cents. I'm happy just seeing the IAM role stuff. Default provider chain would just be icing on the cake :)

**Comment by benwilson512** [comment]
Good arguments. You've convinced me that having the AWS standard defaults pre-configured is a good idea, so per this branch it will no longer be required that anyone put anything in their mix config at all provided they're already setting the aforementioned ENV variables, or are running on an instance with a role configured.

I'm still gonna avoid having folks explicitly call a module, but that provider pattern now sits nicely with other defaults inside ExAws.Config.Defaults.

Gonna test on an instance to make sure it actually works then merge into master.

Thanks for your input!
