### ISSUE TITLE
get_item! empty result

### ISSUE THREAD

**Issue by jschoch** [CargoSense/ex_aws#38]
wondering if {:ok, %{}} is correct on an empty result.  {:ok,nil} may be better.  maybe not for get_item!, but get_item should return an empty map if you expect people to use case

this smells a bit
```elixir
case Dynamo.get_item!(..) do
  {:ok,map} when map == %{} -> ....
  #  {:ok,%{}} always matches so we can't use it with case...

```

**Comment by benwilson512** [comment]
I'm not sure how you're getting an `{:ok, val}` response from `get_item!`. `get_item!` matches on the result of `get_item` to ensure that you either get the desired object back or a match error.

Now, with respect to `get_item`, the empty map you're getting is simply the value returned by Dynamo. The value of a successful query is `{"Item":json_item}` but since dynamo does not put JSON keys for values that are nil, a missing item will mean that there's no "Item" key. The other reason that nil would be improper is that the following query needs to work to match the Dynamo API:
```
Dynamo.get_item("Users", email: "non-existing-email", return_consumed_capacity: true)
```

This query will return JSON like
```
"ConsumedCapacity": {
    "CapacityUnits": 1,
    "TableName": "Thread"
}
```
meaning an elixir response like: `{:ok, %{"ConsumedCapacity" => stuff}}`

SO where does this leave us? If you want a conditional case like in your example what you should do is
```elixir
case Dynamo.get_item(...) do
  {:ok, %{"Item" => item}} -> do_stuff_with(item)
  _ -> handle_no_item
end
```

**Comment by jschoch** [comment]
it raises a match error for me on an non existing item.

```elixir 
Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ExAws.Dynamo.get_item!("Graph-test",%{hash_key: "a",range_key: "0"})
** (MatchError) no match of right hand side value: {:ok, %{}}
    lib/ex_aws/dynamo/impl.ex:184: ExAws.Dynamo.Impl.get_item!/4
```
perhaps it should do the following vs raise a match error 

```elixir
{:ok, %{"Items" => []}}
```

**Comment by benwilson512** [comment]
What do you mean by "it"? API functions in ExAws return `{:ok | :error, result}` tuples. For convenience, there are also bang functions which either return the desired item or raise a match error. This is a very common Elixir idiom. Non bang versions return tuples, bang functions don't, that part isn't going to change.

Your suggestion then is  that the non bang version return `{:ok, %{"Item" => nil}}` ? As I mentioned before, I'm not sure I see the value. Dynamo doesn't return anything, I don't see what is gained by making something up. It also introduces an inconsistency, because sometimes I would be modifying Dynamo's return value to include a key set to `nil`, and sometimes I would not be. Unless you're suggesting I should add every possible return key and set it to `nil`?

Dynamo's convention is to leave out keys in a JSON blob if they value is nil, a convention which holds for both data sent to it and data returning from it. I don't see any motivation for deviating from that convention for this API. Pattern matching concerns seem answered by the example I gave prior.

I'm happy to re-evaluate if there's a compelling case for it, but I don't see it so far.
