### ISSUE TITLE
Abort failed multi-part upload

### ISSUE THREAD

**Issue by asgoel** [CargoSense/ex_aws#383]
When using the `S3.upload` API, what's 1) the best way to detect if the upload has failed, and 2) abort the multipart upload if so? It looks like that API doesn't take care of aborting on error.

**Comment by benwilson512** [comment]
It depends a bit on what fails. If it fails to initiate then you'll just get back a regular `{:error` tuple for `ExAws.request` and an exception for `ExAws.request!`.

A given part failing will lead to a crash, as it wasn't entirely clear how best to return an error with multiple concurrent parts all uploading.

If handling part way through failure is something you want to do then I would start the upload inside a task, and then use Task.yield to ascertain the success or failure of the operation.

> It looks like that API doesn't take care of aborting on error.

If by this you mean that ExAws doesn't automatically run an Abort Multipart Upload operation then no, and that's intentional. If you've uploaded several gigs worth of a file it'd be better to try to resume from that instead of aborting. I definitely cannot assume that that's what you want to do.
