### ISSUE TITLE
Support for LocalStack

### ISSUE THREAD

**Issue by CadmusRhys** [CargoSense/ex_aws#467]
Hi,

It'd be great if ex_aws could allow for specification of aws endpoint (as is possible in the aws cli), as then our team can use [local stack](https://localstack.cloud/) which provides a local aws cloud for local development.

A potential implementation would be to set the endpoint in the config and thus we can differentiate our dev and a prod config.  The endpoint could default point to aws.

Thanks!

**Comment by xfumihiro** [comment]
You can set the endpoint via config as

```
config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 4572,
  region: "us-east-1"
```

**Comment by benwilson512** [comment]
Indeed, I'm pretty sure this is already possible. Please re-open if you can't make this work.

**Comment by alexserver** [comment]
I know this issue is closed, but can the repo owners to put this very important thing in the documentation ?
there's no place where the documentation says you can set a port, and I only discovered this googling and coming to this issue.
if you put this in the documentation, you will save a lot of lost souls
please

**Comment by bernardd** [comment]
@alexserver It's, like, right at the top of the section entitled "Configuration". I have no idea where else you think it should live: https://hexdocs.pm/ex_aws_s3/2.3.0/ExAws.S3.html#module-configuration

**Comment by jbonet** [comment]
This is not true, its only for S3, but not for every other service. How to do this for Kinesis?
