### ISSUE TITLE
Uploads to S3 failing

### ISSUE THREAD

**Issue by mschae** [CargoSense/ex_aws#47]
This is going to be a very unsatisfactory issue report, I apologise in advance.

This was reported by @ericmj and experienced by myself in one of our projects.

It seems that sometimes uploads to S3 stop working. No error is being raised and it looks like they just stall. Data doesn't make it into S3 but again: No error.

Best guess right now is that requests are timing out and the pool only holds one connection.

Possible fixes:

- Timeouts (e.g. recv_timeout, pool timeout, etc.)
- Increase pool size

**Comment by mschae** [comment]
Looks like the default_pool size is 50 and default_pool is indeed enabled by default.

That means that if 50 requests don't get a reply HTTPoison will silently die.

**Comment by benwilson512** [comment]
I think as a first step here I'm going to write an http client adapter to use pure Hackney w/o some of the bad defaults set by httpoison. This will handle the recv_timeout issue.

Base on underlying issues with hackeny pool I think it makes sense to set pool false so that it doesn't try to reuse connections.

**Comment by mschae** [comment]
I don't think we need to forego HTTPoison. Not it's fault and we can just override the bad defaults.

**Comment by benwilson512** [comment]
True. Well at a minimum I'll write an adapter for it such that the defaults are overridden.
