### ISSUE TITLE
Chunk S3 delete_multiple_objects to 1000 of objects

### ISSUE THREAD

**Issue by ericmj** [CargoSense/ex_aws#75]
From https://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html

> The Multi-Object Delete request contains a list of up to 1000 keys that you want to delete.

**Comment by benwilson512** [comment]
Is this related to the discussion we had in IRC?

**Comment by ericmj** [comment]
No, this is the same limitation as listing objects has. If the user gives more than 1000 keys to the function amazon will not accept the request as they will only delete 1000 at a time.

**Comment by benwilson512** [comment]
I see. So you'd like some `delete_all_objects/N` function that would call `delete_multiple_objects/N` in chunks of 1000?

**Comment by ericmj** [comment]
Yes, or at least error if I give more than 1000 keys.

**Comment by benwilson512** [comment]
The policy I've taken towards AWS validations at the moment is to by and large let AWS do the validating and return an error. The validations AWS services perform upon the incoming data can get exceptionally complex, and many are not even possible to check pre-request. If you aren't actually doing anything with the results of the function, calling the ! variety will raise an error from AWS that will explain the issue. However, not all functions have ! variants so THAT I definitely need to fix.

I do see the value of doing simple checks on things like list length, but on the whole I'd rather put work towards surfacing the validations AWS already performs better over duplicating those validations as much as is possible.

**Comment by ericmj** [comment]
I really like that `list_objects` does multiple requests for me. Why not do the same for `delete_all_objects`?

**Comment by benwilson512** [comment]
Sorry, I addressed one idea and not the other. I'm absolutely down for creating a `delete_all_objects/N` that does multiple requests. I was simply addressing the idea of whether or not ExAws out to try to validate data sent to the S3 action `delete_multiple_objects` in the general context of validating data pre-request. I definitely think the best route here is `delete_all_objects/N`, some documentation explaining the differences, and bang functions to make sure that if you ARE calling `delete_multiple_objects` directly there's a way to have it easily raise on error.

**Comment by ericmj** [comment]
Is there any reason to keep the old one that doesn't make multiple requests?

On Wed, Sep 16, 2015 at 6:25 PM, Ben Wilson <notifications@github.com>
wrote:

> Sorry, I addressed one idea and not the other. I'm absolutely down for
> creating a delete_all_objects/N that does multiple requests. I was simply
> addressing the idea of whether or not ExAws out to try to validate data
> sent to the S3 action delete_multiple_objects in the general context of
> validating data pre-request. I definitely think the best route here is
> delete_all_objects/N, some documentation explaining the differences, and
> bang functions to make sure that if you ARE calling
> delete_multiple_objects directly there's a way to have it easily raise on
> error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CargoSense/ex_aws/issues/75#issuecomment-140794073>.
>



-- 
Eric Meadows-Jönsson

**Comment by benwilson512** [comment]
My approach thus far is to always have a corresponding elixir function for each AWS action. The value there is that if for example someone wants to make a delete_all_objects function that operates concurrently the underlying delete_multiple_objects function exists to handle the S3 action, so that the user can focus on their intended use.

In some upcoming changes I'm making to facilitate generating code from AWS specs there will be a nicer distinction between fundamental AWS actions (found in the `$service.Core` module) and higher level functionality that add onto or even replace more obnoxious lower level ones. At the moment I need to support both.

**Comment by ericmj** [comment]
I'm not talking about concurrency here. I am talking about bringing the
convenience of list_objects to delete_multiple_objects. There is no
list_objects function that won't do multiple requests so why should there
be such a function for delete_multiple_objects? It's inconsistent. Or are
you saying that such a function should exist for list_objects also?

On Wed, Sep 16, 2015 at 6:33 PM, Ben Wilson <notifications@github.com>
wrote:

> My approach thus far is to always have a corresponding elixir function for
> each AWS action. The value there is that if for example someone wants to
> make a delete_all_objects function that operates concurrently the
> underlying delete_multiple_objects function exists to handle the S3 action,
> so that the user can focus on their intended use.
>
> In some upcoming changes I'm making to facilitate generating code from AWS
> specs there will be a nicer distinction between fundamental AWS actions
> (found in the $service.Core module) and higher level functionality that
> add onto or even replace more obnoxious lower level ones. At the moment I
> need to support both.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CargoSense/ex_aws/issues/75#issuecomment-140796085>.
>



-- 
Eric Meadows-Jönsson

**Comment by benwilson512** [comment]
list_objects https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3/impl.ex#L52 does not in fact do multiple requests. `stream_objects!` does by building on top of `list_objects` https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3/lazy.ex#L4

**Comment by ericmj** [comment]
I see, now I understand better. So I guess I am asking for the `stream_objects!` equivalent of `delete_multiple_objects`.

**Comment by benwilson512** [comment]
Can do :+1:
