### ISSUE TITLE
sweet_xml not optional

### ISSUE THREAD

**Issue by stocks29** [CargoSense/ex_aws#95]
```
== Compilation error on file lib/ex_aws/s3/parsers.ex ==
** (CompileError) lib/ex_aws/s3/parsers.ex:3: module SweetXml is not loaded and could not be found
    (elixir) expanding macro: Kernel.if/2
    lib/ex_aws/s3/parsers.ex:2: ExAws.S3.Parsers (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

In addition, the sweet_xml dependency requires an older version:

```
Looking up alternatives for conflicting requirements on sweet_xml
  Activated version: 0.5.0
  From mix.exs: ~> 0.5.0
  From ex_aws v0.4.11: ~> 0.2.1
```

It would be nice to either make this truly optional or at least upgrade the dep to the latest version.

**Comment by benwilson512** [comment]
Hey I've been meaning to push a new release, can you try github master real quick? I believe it's fixed there.

**Comment by myronmarston** [comment]
In master it looks like the dependency is:

``` elixir
{:sweet_xml, "~> 0.4.0", optional: true}
```

Any reason to only allow `0.4.x` versions? If you're running Elixir 1.1 (and we are), sweet xml 0.4 produces a warning because its elixir version specifier says it only supports Elixir 1.0.  Sweet xml 0.5 relaxes the Elixir version specifier and no longer generates a warning.  It'd be nice if you're version specifier wasn't so strict.  For the other libs you depend on you specify only two digits of precision, allowing minor version upgrades.  Does `sweet_xml` require a stricter versioning policy?

**Comment by benwilson512** [comment]
I can relax it. Feel free to use `override: true` in the mean time.

**Comment by myronmarston** [comment]
I never even knew about that option!

**Comment by JustMikey** [comment]
Are there any obstacles to relax the version?

**Comment by benwilson512** [comment]
No, it's been relaxed in the latest release.
